### ISSUE TITLE
The Random Password Can Not Login The System

### ISSUE THREAD

**Issue by inspuradmin** [inspursoft/inOS#4]
Use this script can build a image and boot from ramdisk.
But there is a critical issue can not fix now:
The lxc create a container use a random password for root in file /var/lib/lxc//tmp_root_pass. When boot up the container, need to use the random password first and change it. But in the inOS boot from ramdisk, the random password can not login the system.

**Comment by Robin-Mao** [comment]
Fixed in PR #5

**Comment by inspuradmin** [comment]
LGTM
